package com.example.mad_assignment_1

import android.app.Activity
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import android.content.Intent
import android.widget.Toast
import androidx.lifecycle.ViewModelProvider


import com.example.mad_assignment_1.databinding.FragmentNewUserBinding

import androidx.recyclerview.widget.LinearLayoutManager


class NewUserFragment: Fragment() {
    private lateinit var binding: FragmentNewUserBinding
    private lateinit var menuInformationModel: MenuInformationModel
    private var selectedAvatarResId: Int = R.drawable.avatar


    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        menuInformationModel = ViewModelProvider(requireActivity()).get(MenuInformationModel::class.java)
        binding = FragmentNewUserBinding.inflate(inflater, container, false)
        binding.avatarRecyclerView.layoutManager =  LinearLayoutManager(requireContext(), LinearLayoutManager.HORIZONTAL, false)
        binding.avatarRecyclerView.adapter = AvatarAdapter(menuInformationModel.imageResourceMap) { avatarResId ->
            selectedAvatarResId = avatarResId // Update selected avatar
            binding.avatarPreview.setImageResource(menuInformationModel.getImageResource(selectedAvatarResId))
        }
        binding.addButton.setOnClickListener{
            val userName = binding.editTextText.text.toString()

            val newUser = UserEntity(
                userID = 0,  // The ID will be auto-generated by Room
                name = userName,
                profilePic = selectedAvatarResId,

            )
            menuInformationModel.addUser(newUser)
           parentFragmentManager.beginTransaction()
               .replace(R.id.mainMenuContainer, UserViewFragment())
               .commit()
        }
        binding.returnButton.setOnClickListener{
            parentFragmentManager.beginTransaction()
                .replace(R.id.mainMenuContainer, UserViewFragment())
                .commit()
        }
        return binding.root


    }
}